# Generated by Django 2.2.4 on 2019-10-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycart', '0026_orders_product_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='Image',
            field=models.ImageField(null=True, upload_to='shop/images'),
        ),
        migrations.AddField(
            model_name='orders',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='desc',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='product_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='subcategory',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='usern',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
