# Generated by Django 2.2.4 on 2019-10-11 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycart', '0027_auto_20191011_2343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='Image',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='category',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='price',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='usern',
        ),
    ]
