# Generated by Django 2.2.4 on 2019-10-11 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycart', '0029_orders_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='date',
        ),
    ]
