# Generated by Django 2.2.4 on 2019-11-09 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycart', '0030_remove_orders_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='zip_code',
            field=models.IntegerField(default=''),
        ),
    ]
